// <auto-generated />
using App42.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace App42.Server.Migrations
{
    [DbContext(typeof(App42Context))]
    [Migration("20171016171732_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("App42.Common.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("Discriminator");

                    b.Property<int>("TripId");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Events");

                    b.HasDiscriminator<int>("Discriminator");
                });

            modelBuilder.Entity("App42.Common.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("InProgress");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("App42.Common.BatteryEvent", b =>
                {
                    b.HasBaseType("App42.Common.Event");

                    b.Property<int>("Charge");

                    b.ToTable("BatteryEvent");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("App42.Common.LocationEvent", b =>
                {
                    b.HasBaseType("App42.Common.Event");

                    b.Property<float>("Accuracy");

                    b.Property<double>("Lat");

                    b.Property<double>("Lon");

                    b.Property<float>("Speed");

                    b.ToTable("LocationEvent");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("App42.Common.Event", b =>
                {
                    b.HasOne("App42.Common.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
